version: '3.2'

services:
    redis:
        image: redis:4.0.11
        command: ['redis-server', '--appendonly', 'yes']
        ports:
            - 6379:6379
        restart: unless-stopped
        networks:
            - net

    # http://localhost:8082/
    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        restart: unless-stopped
        ports:
            - 8082:80
        environment:
            REDIS_1_HOST: redis
            REDIS_1_PORT: 6379
        networks:
            - net
networks:
    net:
        driver: bridge
